language: ruby
before_install: gem install bundler && bundler -v
gemfile:
  - gemfiles/rspec2.gemfile
  - gemfiles/rspec3.gemfile
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: "2.0"
    - rvm: "2.1"
rvm:
  - "2.0"
  - "2.1"
  - "2.2.7"
  - "2.3.4"
  - "2.4.1"
  - ruby-head
