language: ruby
before_install: gem install bundler && bundler -v
gemfile:
  - gemfiles/rspec2.gemfile
  - gemfiles/rspec3.gemfile
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0-p648
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: 1.9.2
    - rvm: 1.9.3
  fast_finish: true
